/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static DB_Connection.DBConnection.getConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author 5410
 */
public class NhanVienForm extends javax.swing.JPanel {

    /**
     * Creates new form Nhan_Vien  
     */
    public NhanVienForm() {
        initComponents();
           loadNhanVien();
           
    }

    public void loadNhanVien() {
        DefaultTableModel model = (DefaultTableModel) NhanVienTable.getModel();
        model.setRowCount(0); // clear table
        try (Connection con = DB_Connection.DBConnection.getConnection(); Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM NhanVien")) {

            int stt = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    stt++,
                    rs.getString("MaNhanVien"),
                    rs.getString("TenNhanVien"),
                    rs.getString("ChucVu"),
                    rs.getString("SoDienThoai"),
                    rs.getString("TaiKhoan"),
                    rs.getString("MatKhau"),
                    rs.getString("VaiTro")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
   
    public static void main(String[] args) {
        getConnection(); // Gọi thử kết nối
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        maNV = new javax.swing.JLabel();
        matKhau = new javax.swing.JLabel();
        taiKhoan = new javax.swing.JLabel();
        vaiTro = new javax.swing.JLabel();
        tenNV = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        maNhanVienText = new javax.swing.JTextField();
        tenNVText = new javax.swing.JTextField();
        SDTText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chucVu = new javax.swing.JLabel();
        quanLybtn = new javax.swing.JRadioButton();
        nhanVienbtn = new javax.swing.JRadioButton();
        taiKhoanText = new javax.swing.JTextField();
        matKhauText = new javax.swing.JTextField();
        vaiTrocbb = new javax.swing.JComboBox<>();
        themNVbtn = new javax.swing.JButton();
        xoaNVbtn = new javax.swing.JButton();
        suaNVbtn = new javax.swing.JButton();
        timKiem = new javax.swing.JLabel();
        timKiemText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NhanVienTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        maNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maNV.setText("Mã nhân viên");

        matKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        matKhau.setText("Mật khẩu");

        taiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taiKhoan.setText("Tài khoản");

        vaiTro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaiTro.setText("Vai trò");

        tenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenNV.setText("Tên nhân viên");

        sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sdt.setText("Số điện thoại");

        maNhanVienText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maNhanVienText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNhanVienTextActionPerformed(evt);
            }
        });

        tenNVText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tenNVText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenNVTextActionPerformed(evt);
            }
        });

        SDTText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SDTText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SDTTextActionPerformed(evt);
            }
        });

        chucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chucVu.setText("Chức vụ");

        buttonGroup1.add(quanLybtn);
        quanLybtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quanLybtn.setText("Quản lý");

        buttonGroup1.add(nhanVienbtn);
        nhanVienbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nhanVienbtn.setText("Nhân viên");
        nhanVienbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVienbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhanVienbtn)
                    .addComponent(quanLybtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chucVu)
                    .addComponent(quanLybtn))
                .addGap(18, 18, 18)
                .addComponent(nhanVienbtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        taiKhoanText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taiKhoanText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taiKhoanTextActionPerformed(evt);
            }
        });

        matKhauText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        matKhauText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matKhauTextActionPerformed(evt);
            }
        });

        vaiTrocbb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vaiTrocbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu ngân", "Bảo vệ", "Vệ sinh" }));

        themNVbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        themNVbtn.setText("ADD");
        themNVbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNVbtnActionPerformed(evt);
            }
        });

        xoaNVbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xoaNVbtn.setText("DELETE");
        xoaNVbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaNVbtnActionPerformed(evt);
            }
        });

        suaNVbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suaNVbtn.setText("UPDATE");
        suaNVbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaNVbtnActionPerformed(evt);
            }
        });

        timKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timKiem.setText("Tìm kiếm");

        timKiemText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timKiemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(maNV)
                                .addGap(32, 32, 32)
                                .addComponent(maNhanVienText))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(SDTText)))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(themNVbtn)
                        .addGap(40, 40, 40)
                        .addComponent(xoaNVbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(suaNVbtn)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenNVText)
                            .addComponent(matKhauText)
                            .addComponent(taiKhoanText)
                            .addComponent(vaiTrocbb, 0, 191, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(timKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(timKiemText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNV)
                    .addComponent(tenNV)
                    .addComponent(maNhanVienText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenNVText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaiTro)
                    .addComponent(sdt)
                    .addComponent(SDTText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaiTrocbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(matKhauText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(taiKhoan)
                                    .addComponent(taiKhoanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addComponent(matKhau))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themNVbtn)
                    .addComponent(xoaNVbtn)
                    .addComponent(suaNVbtn)
                    .addComponent(timKiem)
                    .addComponent(timKiemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NhanVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Số điện thoại", "Tài khoản", "Mật khẩu", "Vai trò"
            }
        ));
        NhanVienTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(NhanVienTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maNhanVienTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNhanVienTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maNhanVienTextActionPerformed

    private void tenNVTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenNVTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenNVTextActionPerformed

    private void SDTTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SDTTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SDTTextActionPerformed

    private void nhanVienbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVienbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanVienbtnActionPerformed

    private void taiKhoanTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taiKhoanTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taiKhoanTextActionPerformed

    private void matKhauTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matKhauTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matKhauTextActionPerformed

    private void themNVbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNVbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themNVbtnActionPerformed

    private void xoaNVbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaNVbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoaNVbtnActionPerformed

    private void suaNVbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaNVbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suaNVbtnActionPerformed

    private void timKiemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemTextActionPerformed

    private void NhanVienTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NhanVienTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable NhanVienTable;
    private javax.swing.JTextField SDTText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maNV;
    private javax.swing.JTextField maNhanVienText;
    private javax.swing.JLabel matKhau;
    private javax.swing.JTextField matKhauText;
    private javax.swing.JRadioButton nhanVienbtn;
    private javax.swing.JRadioButton quanLybtn;
    private javax.swing.JLabel sdt;
    private javax.swing.JButton suaNVbtn;
    private javax.swing.JLabel taiKhoan;
    private javax.swing.JTextField taiKhoanText;
    private javax.swing.JLabel tenNV;
    private javax.swing.JTextField tenNVText;
    private javax.swing.JButton themNVbtn;
    private javax.swing.JLabel timKiem;
    private javax.swing.JTextField timKiemText;
    private javax.swing.JLabel vaiTro;
    private javax.swing.JComboBox<String> vaiTrocbb;
    private javax.swing.JButton xoaNVbtn;
    // End of variables declaration//GEN-END:variables
}
