/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Entity.KhachHang;
import Dao.KhachHangRepository;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ViewKhachHang extends javax.swing.JFrame {

    private final KhachHangRepository khachHangRepository = new KhachHangRepository();
    private DefaultTableModel mol = new DefaultTableModel();

    /**
     * Creates new form ViewKhachHang
     */
    public ViewKhachHang() {
        initComponents(); // Khởi tạo các thành phần giao diện (do NetBeans tạo)
        this.setLocationRelativeTo(null); // Đặt cửa sổ ở giữa màn hình
        txtMa.setEnabled(false);
        // Khởi tạo mô hình bảng
        mol = (DefaultTableModel) tblKhachHang.getModel();

        // Đổ dữ liệu vào bảng
        this.fillTableKH(khachHangRepository.getAll()); // Bảng khách hàng
    }

    private String getSafeString(Object value) {
        return value != null ? value.toString() : "";
    }

    public void fillTableKH(ArrayList<KhachHang> list) {
        mol.setRowCount(0); // Xóa dữ liệu cũ trong bảng
        for (KhachHang kh : list) {
            Object[] rowData = kh.toDataRow(); // Lấy dữ liệu từ toDataRow (5 cột: MaKH, TenKH, SoDT, DiaChi, DiemTichLuy)
            mol.addRow(rowData); // Thêm trực tiếp mảng rowData vào bảng
        }
        if (list.isEmpty()) {
            System.out.println("Cảnh báo: Danh sách khách hàng rỗng!");
        }
    }
    
    private void clearForm() {
        txtMa.setText(""); // Reset Mã khách hàng (có thể để trống vì IDENTITY)
        txtTen.setText(""); // Reset Tên khách hàng
        txtSdt.setText(""); // Reset Số điện thoại
        txtDiaChi.setText(""); // Reset Địa chỉ
        txtDiemTichLuy.setText(""); // Reset Điểm tích lũy
        txtTen.requestFocus(); // Đặt con trỏ về trường Tên khách hàng
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDiemTichLuy = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Mã Khách Hàng: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tên Khách Hàng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Số Điện Thoại:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Địa Chỉ:");

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnClear.setText("Làm Mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Điểm Tích Lũy:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Tìm Kiếm:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại ", "Địa Chỉ", "Điểm Tích Lũy"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnthem)
                        .addGap(115, 115, 115)
                        .addComponent(btnsua)
                        .addGap(75, 75, 75)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiemTichLuy))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTen))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtSdt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtDiemTichLuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsua)
                    .addComponent(btnClear)
                    .addComponent(btnthem))
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked

        int row = tblKhachHang.getSelectedRow();
        if (row >= 0) {
            // Hiển thị dữ liệu từ bảng lên form
            txtMa.setText(getSafeString(tblKhachHang.getValueAt(row, 0))); // Mã khách hàng (cột 0)
            txtTen.setText(getSafeString(tblKhachHang.getValueAt(row, 1))); // Tên khách hàng (cột 1)
            txtSdt.setText(getSafeString(tblKhachHang.getValueAt(row, 2))); // Số điện thoại (cột 2)
            txtDiaChi.setText(getSafeString(tblKhachHang.getValueAt(row, 3))); // Địa chỉ (cột 3)

            // Xử lý điểm tích lũy: loại bỏ ".0" và định dạng với dấu phẩy
            String diemTichLuyStr = tblKhachHang.getValueAt(row, 4).toString().replace(",", ""); // Loại bỏ dấu phẩy hiện có
            try {
                BigDecimal diemTichLuy = new BigDecimal(diemTichLuyStr);
                // Định dạng với dấu phẩy, bỏ phần thập phân .0
                DecimalFormat df = new DecimalFormat("#,###");
                txtDiemTichLuy.setText(df.format(diemTichLuy));
            } catch (NumberFormatException e) {
                // Nếu không parse được, giữ nguyên giá trị đã loại bỏ dấu phẩy
                txtDiemTichLuy.setText(diemTichLuyStr);
            }

        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa thông tin khách hàng này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Lấy thông tin từ giao diện (không trim ngay để kiểm tra khoảng trống)
            String maKhachHangStr = txtMa.getText();
            String tenKhachHangInput = txtTen.getText();
            String soDienThoaiInput = txtSdt.getText();
            String diaChiInput = txtDiaChi.getText();
            String diemTichLuyStrInput = txtDiemTichLuy.getText();

            // Kiểm tra khoảng trống ở đầu hoặc cuối
            if (!tenKhachHangInput.equals(tenKhachHangInput.trim())) {
                JOptionPane.showMessageDialog(this, "Tên khách hàng không được chứa khoảng trống ở đầu hoặc cuối");
                txtTen.requestFocus();
                return;
            }
            if (!soDienThoaiInput.equals(soDienThoaiInput.trim())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không được chứa khoảng trống ở đầu hoặc cuối");
                txtSdt.requestFocus();
                return;
            }
            if (!diaChiInput.equals(diaChiInput.trim())) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được chứa khoảng trống ở đầu hoặc cuối");
                txtDiaChi.requestFocus();
                return;
            }
            if (!diemTichLuyStrInput.equals(diemTichLuyStrInput.trim())) {
                JOptionPane.showMessageDialog(this, "Điểm tích lũy không được chứa khoảng trống ở đầu hoặc cuối");
                txtDiemTichLuy.requestFocus();
                return;
            }

            // Trim sau khi kiểm tra
            String tenKhachHang = tenKhachHangInput.trim();
            String soDienThoai = soDienThoaiInput.trim();
            String diaChi = diaChiInput.trim();
            String diemTichLuyStr = diemTichLuyStrInput.trim();

            // Kiểm tra các trường không được để trống
            if (tenKhachHang.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên khách hàng");
                txtTen.requestFocus();
                return;
            }
            if (soDienThoai.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập số điện thoại");
                txtSdt.requestFocus();
                return;
            }
            if (diaChi.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập địa chỉ");
                txtDiaChi.requestFocus();
                return;
            }
            if (diemTichLuyStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập điểm tích lũy");
                txtDiemTichLuy.requestFocus();
                return;
            }

            // Parse MaKhachHang (vì là int)
            int maKhachHang;
            try {
                maKhachHang = Integer.parseInt(maKhachHangStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng không hợp lệ");
                txtMa.requestFocus();
                return;
            }

            // Validate và parse DiemTichLuy (hỗ trợ dấu phẩy)
            int diemTichLuy;
            try {
                String diemTichLuyStrCleaned = diemTichLuyStr.replace(".", ""); // Loại bỏ dấu chấm nếu có
                if (diemTichLuyStrCleaned.contains(",")) {
                    JOptionPane.showMessageDialog(this, "Điểm tích lũy không được chứa dấu phẩy (,)");
                    txtDiemTichLuy.requestFocus();
                    return;
                }
                diemTichLuy = Integer.parseInt(diemTichLuyStrCleaned);
                if (diemTichLuy < 0) {
                    JOptionPane.showMessageDialog(this, "Điểm tích lũy không được âm");
                    txtDiemTichLuy.requestFocus();
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Điểm tích lũy phải là số nguyên dương");
                txtDiemTichLuy.requestFocus();
                return;
            }

            // Gọi phương thức cập nhật
            KhachHangRepository repository = new KhachHangRepository();
            boolean isUpdated = repository.updateKhachHang(maKhachHang, tenKhachHang, soDienThoai, diaChi, diemTichLuy);

            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin khách hàng thành công!");
                // Làm mới bảng và form
                ArrayList<KhachHang> list = repository.getAll();
                mol.setRowCount(0);
                for (KhachHang kh : list) {
                    mol.addRow(kh.toDataRow());
                }
                clearForm(); // Reset form sau khi sửa
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin khách hàng thất bại.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn làm mới form này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Làm mới form
        clearForm();
    
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
        String searchText = txtSearch.getText().trim().toLowerCase();
        ArrayList<KhachHang> fullList = khachHangRepository.getAll();
        ArrayList<KhachHang> filteredList = new ArrayList<>();

        // Lọc danh sách theo TenKhachHang hoặc SoDienThoai
        for (KhachHang kh : fullList) {
            String tenKhachHang = kh.getTenKhachHang() != null ? kh.getTenKhachHang().toLowerCase() : "";
            String soDienThoai = kh.getSoDienThoai() != null ? kh.getSoDienThoai().toLowerCase() : "";
            if (tenKhachHang.contains(searchText) || soDienThoai.contains(searchText)) {
                filteredList.add(kh);
            }
        }

        // Cập nhật bảng với danh sách đã lọc
        mol.setRowCount(0);
        for (KhachHang kh : filteredList) {
            mol.addRow(kh.toDataRow());
        }
    

   
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm khách hàng này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            String tenKhachHangInput = txtTen.getText();
            String soDienThoaiInput = txtSdt.getText();
            String diaChiInput = txtDiaChi.getText();
            String diemTichLuyStrInput = txtDiemTichLuy.getText();

            // Kiểm tra khoảng trắng đầu/cuối
            if (!tenKhachHangInput.equals(tenKhachHangInput.trim())) {
                JOptionPane.showMessageDialog(this, "Tên khách hàng không được chứa khoảng trắng ở đầu hoặc cuối");
                txtTen.requestFocus();
                return;
            }
            if (!soDienThoaiInput.equals(soDienThoaiInput.trim())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không được chứa khoảng trắng ở đầu hoặc cuối");
                txtSdt.requestFocus();
                return;
            }
            if (!diemTichLuyStrInput.equals(diemTichLuyStrInput.trim())) {
                JOptionPane.showMessageDialog(this, "Điểm tích lũy không được chứa khoảng trắng ở đầu hoặc cuối");
                txtDiemTichLuy.requestFocus();
                return;
            }

            // Trim dữ liệu
            String tenKhachHang = tenKhachHangInput.trim();
            String soDienThoai = soDienThoaiInput.trim();
            String diaChi = diaChiInput.trim();
            String diemTichLuyStr = diemTichLuyStrInput.trim();

            // Validate tên khách hàng
            if (tenKhachHang.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên khách hàng không được để trống");
                txtTen.requestFocus();
                return;
            }
            if (!tenKhachHang.matches("[\\p{L}\\s]+")) {
                JOptionPane.showMessageDialog(this, "Tên khách hàng chỉ được chứa chữ và khoảng trắng");
                txtTen.requestFocus();
                return;
            }

            // Validate số điện thoại
            if (soDienThoai.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống");
                txtSdt.requestFocus();
                return;
            }

            // Validate điểm tích lũy
            int diemTichLuy = 0;
            try {
                diemTichLuy = Integer.parseInt(diemTichLuyStr);
                if (diemTichLuy < 0) {
                    JOptionPane.showMessageDialog(this, "Điểm tích lũy không được âm");
                    txtDiemTichLuy.requestFocus();
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Điểm tích lũy phải là số nguyên");
                txtDiemTichLuy.requestFocus();
                return;
            }

            // Gọi repository để thêm khách hàng
            KhachHangRepository repository = new KhachHangRepository();
            KhachHang kh = new KhachHang(tenKhachHang, soDienThoai, diaChi, diemTichLuy);

            int idMoi = repository.themKhachHang(kh);

            if (idMoi > 0) {
                JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
                // Làm mới bảng
                ArrayList<KhachHang> list = repository.getAll();
                DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
                model.setRowCount(0);
                for (KhachHang khach : list) {
                    model.addRow(khach.toDataRow());
                }
                clearForm(); // Reset form sau khi thêm
            } else {
                JOptionPane.showMessageDialog(this, "Thêm khách hàng thất bại.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKhachHang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKhachHang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKhachHang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKhachHang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemTichLuy;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
